### ISSUE TITLE
'Namespace' object has no attribute 'unauthorised'

### ISSUE THREAD

**Issue by dakota-marshall** [Serene-Arc/ogsdownloader#5]
Installed the module via instructions, and ran the following:

```bash
python3 -m ogsdownloader ./ -u $my_username -i --authorised -v
```
Spat out:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dakota-marshall/.local/lib/python3.10/site-packages/ogsdownloader/__main__.py", line 124, in <module>
    entry()
  File "/home/dakota-marshall/.local/lib/python3.10/site-packages/ogsdownloader/__main__.py", line 120, in entry
    main(args)
  File "/home/dakota-marshall/.local/lib/python3.10/site-packages/ogsdownloader/__main__.py", line 72, in main
    if not config.has_option('DEFAULT', 'username') and not args.username and not args.unauthorised:
AttributeError: 'Namespace' object has no attribute 'unauthorised'. Did you mean: 'authorised'?
```

I removed `and not args.unauthorised` from the if statement, and it worked as expected.

**Comment by Serene-Arc** [comment]
Fixed in b96a116
